gwy: added wait to allow manual intervention if wsgi server fails

diff --git a/gateway/compose/local/django/start b/gateway/compose/local/django/start
--- a/gateway/compose/local/django/start
+++ b/gateway/compose/local/django/start
@@ -8,8 +8,12 @@ APP_DIR="/app"
 function echo_wait_and_quit() {
     local message="$1"
     echo >&2 "$message"
-    echo >&2 "Waiting for manual input before exiting..."
+
+    # this wait may be useful for manually running manage.py or
+    # other shell commands in the container in case of failure:
+    echo -e >&2 "\033[0;31mGiving time for manual input before exiting...\033[0m"
     sleep 3600
+
     exit 1
 }
 
@@ -40,7 +44,12 @@ function main() {
     }
 
     echo "Starting Uvicorn server..."
-    exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
+    exec uvicorn config.asgi:application \
+        --host 0.0.0.0 \
+        --reload \
+        --reload-include '*.html' || {
+            echo_wait_and_quit "Uvicorn server failed."
+        }
 
 }
 
