gwy: running db migrations on startup

diff --git a/gateway/compose/local/django/start b/gateway/compose/local/django/start
--- a/gateway/compose/local/django/start
+++ b/gateway/compose/local/django/start
@@ -2,15 +2,39 @@
 
 set -euo pipefail
 
-echo "Running database migrations..."
-python manage.py migrate
+APP_DIR="/app"
 
-echo "Initializing OpenSearch indices..."
-python manage.py init_indices || {
-    echo >&2 "Failed to initialize OpenSearch indices. Waiting for manual input."
+# logs a message and waits for manual input before exiting and terminating the container
+function echo_wait_and_quit() {
+    local message="$1"
+    echo >&2 "$message"
+    echo >&2 "Waiting for manual input before exiting..."
     sleep 3600
     exit 1
 }
 
-echo "Starting Uvicorn workers..."
-exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
+function main() {
+
+    pushd "${APP_DIR}" || {
+        echo_wait_and_quit "Failed to change directory to ${APP_DIR}."
+    }
+
+    echo "Applying database migrations..."
+    python manage.py migrate --noinput || {
+        echo_wait_and_quit "Failed to apply database migrations."
+    }
+
+    echo "Initializing OpenSearch indices..."
+    python manage.py init_indices || {
+        echo_wait_and_quit "Failed to initialize OpenSearch indices."
+    }
+
+    echo "Starting Uvicorn server..."
+    exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
+
+}
+
+main "$@" || {
+    echo >&2 "An error occurred while starting the Django application."
+    exit 1
+}
