fixed temp failing sfs tests

diff --git a/gateway/justfile b/gateway/justfile
--- a/gateway/justfile
+++ b/gateway/justfile
@@ -46,6 +46,7 @@ build-full *args:
 [group('utilities')]
 clean:
     #!/usr/bin/env bash
+    set -euo pipefail
     declare -a recursive_directories
     recursive_directories=('__pycache__' '.pytest_cache' '.ruff_cache' 'node_modules')
     for dir in "${recursive_directories[@]}"; do
@@ -144,12 +145,24 @@ dev-setup:
 # prints currently selected environment, for debugging and validation purposes
 [group('utilities')]
 env:
-    @echo -e "\nSelected env:\n"
-    @echo -e "\tEnvironment: \e[34m             '{{ env }}'\e[0m"
-    @echo -e "\tEnvironment file: \e[34m        '{{ env_file }}'\e[0m"
-    @echo -e "\tCompose file: \e[34m            '{{ compose_file }}'\e[0m"
-    @echo -e "\tDocker compose command: \e[34m  '{{ docker_compose }}'\e[0m"
-    @echo -e "\tUV runner command: \e[34m       '{{ uv_runner }}'\e[0m"
+    #!/usr/bin/env bash
+    set -euo pipefail
+    echo -e "\nSelected env:\n"
+    echo -e "\tEnvironment: \e[34m             '{{ env }}'\e[0m"
+    echo -e "\tEnvironment file: \e[34m        '{{ env_file }}'\e[0m"
+    echo -e "\tCompose file: \e[34m            '{{ compose_file }}'\e[0m"
+    echo -e "\tDocker compose command: \e[34m  '{{ docker_compose }}'\e[0m"
+    echo -e "\tUV runner command: \e[34m       '{{ uv_runner }}'\e[0m"
+
+    if ! [ -f "{{ compose_file }}" ]; then
+        echo -e "\n\e[31mError:\e[0m Compose file '{{ compose_file }}' does not exist."
+        exit 1
+    fi
+    if ! [ -f "{{ env_file }}" ]; then
+        echo -e "\n\e[31mError:\e[0m Env file '{{ env_file }}' does not exist." \
+            "Generate secrets for this environment to create it."
+        exit 1
+    fi
 
 # runs GitHub Actions locally
 [group('development')]
@@ -216,6 +229,7 @@ serve-coverage:
 [group('monitoring')]
 snapshot:
     #!/usr/bin/env bash
+    set -euo pipefail
     echo "Creating a snapshot of '{{ env }}' data"
     mkdir -p {{ snapshot_log_dir }}
     log_file="{{ snapshot_log_dir }}/{{ env }}-snapshot-$(date +%Y-%m-%d_%H-%M-%S).log"
@@ -226,6 +240,7 @@ snapshot:
 [group('qa')]
 test *args:
     #!/usr/bin/env bash
+    set -euo pipefail
     echo "Running all tests"
     just test-py {{ args }}
     if [[ "{{ env }}" = "production" ]]; then
@@ -261,6 +276,7 @@ test-js *args:
 [group('service')]
 up *args:
     #!/usr/bin/env bash
+    set -euo pipefail
     echo "Starting sds-gateway in detached mode"
     echo "Environment: '{{ env }}'"
     echo "Compose file: '{{ compose_file }}'"
@@ -298,6 +314,7 @@ uv +args:
 [group('service')]
 watch *args:
     #!/usr/bin/env bash
+    set -euo pipefail
     if [ "{{ env }}" != "local" ]; then
         echo "The 'watch' command is only available in the 'local' environment"
         exit 1
