adjustments to automated secret generation

diff --git a/seaweedfs/justfile b/seaweedfs/justfile
--- a/seaweedfs/justfile
+++ b/seaweedfs/justfile
@@ -60,13 +60,24 @@ down *args:
 # prints currently selected environment
 [group('utilities')]
 env:
-    @echo -e "\nSelected env:\n"
-    @echo -e "\tEnvironment: \e[34m             '{{ env }}'\e[0m"
-    @echo -e "\tEnv file: \e[34m                '{{ env_file }}'\e[0m"
-    @echo -e "\tCompose file: \e[34m            '{{ compose_file }}'\e[0m"
-    @echo -e "\tDocker compose command: \e[34m  '{{ docker_compose }}'\e[0m"
-    @echo -e "\tFiler container: \e[34m         '{{ filer_container }}'\e[0m"
-    @echo -e "\tMaster container: \e[34m        '{{ master_container }}'\e[0m"
+    #!/usr/bin/env bash
+    echo -e "\nSelected env:\n"
+    echo -e "\tEnvironment: \e[34m             '{{ env }}'\e[0m"
+    echo -e "\tEnv file: \e[34m                '{{ env_file }}'\e[0m"
+    echo -e "\tCompose file: \e[34m            '{{ compose_file }}'\e[0m"
+    echo -e "\tDocker compose command: \e[34m  '{{ docker_compose }}'\e[0m"
+    echo -e "\tFiler container: \e[34m         '{{ filer_container }}'\e[0m"
+    echo -e "\tMaster container: \e[34m        '{{ master_container }}'\e[0m"
+
+    if ! [ -f "{{ compose_file }}" ]; then
+        echo -e "\n\e[31mError:\e[0m Compose file '{{ compose_file }}' does not exist."
+        exit 1
+    fi
+    if ! [ -f "{{ env_file }}" ]; then
+        echo -e "\n\e[31mError:\e[0m Env file '{{ env_file }}' does not exist." \
+            "Generate secrets for this environment to create it."
+        exit 1
+    fi
 
 # streams logs until interrupted
 [group('monitoring')]
